id = "blade"
name = "Laravel Blade"
version = "0.0.1"
schema_version = 1
authors = ["Clayton Carter <claytonrcarter@gmail.com>"]
description = "Laravel Blade support for Zed"
repository = "https://github.com/claytonrcarter/zed-language-laravel-blade"

[grammars.blade]
repository = "https://github.com/EmranMR/tree-sitter-blade"
commit = "1c0c868b869acffb9a72f98ac677b8d0b8182605"

[grammars.php_only]
repository = "https://github.com/tree-sitter/tree-sitter-php"
# should use the same commit as https://github.com/zed-industries/zed/blob/main/extensions/php/extension.toml#L16
commit = "8ab93274065cbaf529ea15c24360cfa3348ec9e4"
path = "php_only"
