# should mostly match contents of https://github.com/zed-industries/zed/blob/main/extensions/php/languages/php/config.toml
name = "PHP (w/o opening tag)"
grammar = "php_only"
line_comments = ["// ", "# "]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string"] },
]
collapsed_placeholder = "/* ... */"
word_characters = ["$"]
